from abc import ABC, abstractmethod
from pathlib import Path
from typing import Iterable, Iterator, Protocol

from src.domains.aircraft import Aircraft
from src.domains.capacity import Capacity, CapacitySummary
from src.domains.flight import Flight
from src.domains.flight_event import FlightEvent


class RepositoryProtocol(Protocol):
    def initialize(self) -> None: ...

    def is_exists(self) -> bool: ...

    def bulk_insert_aircraft(self, aircraft: Iterable[Aircraft]) -> int: ...

    def bulk_insert_flights(self, flights: Iterable[Flight]) -> int: ...

    def bulk_insert_capacity(self, capacities: Iterable[Capacity]) -> int: ...

    def bulk_insert_events(self, events: Iterable[FlightEvent]) -> int: ...

    def aggregate_flights(self) -> int: ...

    def calculate_capacity(self) -> int: ...

    def stream_flights(self) -> Iterator[Flight]: ...

    def stream_capacities(
        self,
        origin: str | None = None,
        destination: str | None = None,
        date: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> Iterator[Capacity]: ...

    def stream_capacity_summary(
        self, origin: str, destination: str, date: str | None = None
    ) -> Iterator[CapacitySummary]: ...

    def stream_aircraft(self) -> Iterator[Aircraft]: ...

    def is_file_processed(self, filename: str) -> bool: ...

    def mark_file_processed(self, filename: str) -> None: ...

    def close(self) -> None: ...

    def ingest_csv_direct(self, csv_path: Path) -> int | None: ...

    def export_capacity_csv(self, output_path: Path) -> bool: ...
